/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gameeducation;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String filepath = "musicBg.WAV";
    musicStuff musicObj = new musicStuff();
    public Home() {
        initComponents();
        setLocationRelativeTo(this);
        Seticon();
        this.setTitle("Kuis Seputar TIK");
        musicObj.playMusic(filepath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Mulai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDown = new javax.swing.JLabel();
        lblMute = new javax.swing.JLabel();
        lblUp = new javax.swing.JLabel();
        jLabel_Home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Mulai.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Mulai.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton_Mulai.setText("MULAI");
        jButton_Mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MulaiActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Mulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 270, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET GAME EDU/VolDown (1).png"))); // NOI18N
        lblDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDownMouseClicked(evt);
            }
        });
        jPanel2.add(lblDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        lblMute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET GAME EDU/muteVol (1).png"))); // NOI18N
        lblMute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuteMouseClicked(evt);
            }
        });
        jPanel2.add(lblMute, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        lblUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET GAME EDU/VolUp (1).png"))); // NOI18N
        lblUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpMouseClicked(evt);
            }
        });
        jPanel2.add(lblUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 210, 60));

        jLabel_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET GAME EDU/BG FIX BGT.png"))); // NOI18N
        jPanel1.add(jLabel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_MulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MulaiActionPerformed
        // TODO add your handling code here:
        PilihGame pg = new PilihGame();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_MulaiActionPerformed

    private void lblUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpMouseClicked
        // TODO add your handling code here:
        musicObj.volumeUp();
    }//GEN-LAST:event_lblUpMouseClicked

    private void lblMuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMuteMouseClicked
        // TODO add your handling code here:
        musicObj.muteVol();
    }//GEN-LAST:event_lblMuteMouseClicked

    private void lblDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDownMouseClicked
        // TODO add your handling code here:
        musicObj.volumeDown();
    }//GEN-LAST:event_lblDownMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Mulai;
    private javax.swing.JLabel jLabel_Home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDown;
    private javax.swing.JLabel lblMute;
    private javax.swing.JLabel lblUp;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
