/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gameeducation;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class PilihGame extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public PilihGame() {
        initComponents();
        setLocationRelativeTo(this);
        Seticon();
        this.setTitle("Kuis Seputar TIK");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTb = new javax.swing.JButton();
        btnKuis = new javax.swing.JButton();
        labelInfo = new javax.swing.JLabel();
        btnRules = new javax.swing.JButton();
        labelPrev = new javax.swing.JLabel();
        jLabel_PilihGame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTb.setBackground(new java.awt.Color(204, 204, 204));
        btnTb.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        btnTb.setText("TEBAK GAMBAR");
        btnTb.setBorder(null);
        btnTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbActionPerformed(evt);
            }
        });
        jPanel1.add(btnTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 150, 30));

        btnKuis.setBackground(new java.awt.Color(204, 204, 204));
        btnKuis.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        btnKuis.setText("KUIS");
        btnKuis.setBorder(null);
        btnKuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuisActionPerformed(evt);
            }
        });
        jPanel1.add(btnKuis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 30));

        labelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInfoMouseClicked(evt);
            }
        });
        jPanel1.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 60));

        btnRules.setBackground(new java.awt.Color(204, 204, 204));
        btnRules.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        btnRules.setText("PERATURAN");
        btnRules.setBorder(null);
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });
        jPanel1.add(btnRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 150, 30));

        labelPrev.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        labelPrev.setForeground(new java.awt.Color(255, 255, 255));
        labelPrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrev.setText("Kembali");
        labelPrev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPrevMouseClicked(evt);
            }
        });
        jPanel1.add(labelPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 100, 30));

        jLabel_PilihGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET GAME EDU/BG PG FIX.png"))); // NOI18N
        jPanel1.add(jLabel_PilihGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbActionPerformed
        // TODO add your handling code here:
        PilihGameLevelTg tg = new PilihGameLevelTg();
        tg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTbActionPerformed

    private void btnKuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuisActionPerformed
        // TODO add your handling code here:
        PilihGameLevel pgl = new PilihGameLevel();
        pgl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKuisActionPerformed

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
        // TODO add your handling code here:
        Peraturan rules = new Peraturan();
        rules.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRulesActionPerformed

    private void labelInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInfoMouseClicked
        // TODO add your handling code here:
        Info info = new Info();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelInfoMouseClicked

    private void labelPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPrevMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelPrevMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKuis;
    private javax.swing.JButton btnRules;
    private javax.swing.JButton btnTb;
    private javax.swing.JLabel jLabel_PilihGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelPrev;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
