/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gameeducation;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class PilihGameLevelTg extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public PilihGameLevelTg() {
        initComponents();
        setLocationRelativeTo(this);
        Seticon();
        this.setTitle("Kuis Seputar TIK");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKuisLvl2 = new javax.swing.JButton();
        btnKuisLvl1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_PilihLevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKuisLvl2.setBackground(new java.awt.Color(204, 204, 204));
        btnKuisLvl2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        btnKuisLvl2.setText("LEVEL 2");
        btnKuisLvl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuisLvl2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKuisLvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 240, 40));

        btnKuisLvl1.setBackground(new java.awt.Color(204, 204, 204));
        btnKuisLvl1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        btnKuisLvl1.setText("LEVEL 1");
        btnKuisLvl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuisLvl1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKuisLvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 240, 40));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 90, 50));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 10, 50, 60));

        jLabel_PilihLevel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET GAME EDU/bg pilih level fix.png"))); // NOI18N
        jPanel1.add(jLabel_PilihLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKuisLvl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuisLvl2ActionPerformed
        // TODO add your handling code here:
        TebakGambar2 tg2 = new TebakGambar2();
        tg2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKuisLvl2ActionPerformed

    private void btnKuisLvl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuisLvl1ActionPerformed
        // TODO add your handling code here:
        TebakGambar1 tg1 = new TebakGambar1();
        tg1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKuisLvl1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        PilihGame pg = new PilihGame();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGameLevelTg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGameLevelTg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGameLevelTg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGameLevelTg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGameLevelTg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKuisLvl1;
    private javax.swing.JButton btnKuisLvl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_PilihLevel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
